### ISSUE TITLE
将生产编号由 器具生产信息实体 中删除 ，添加到器具使用信息 实体中。

### ISSUE THREAD

**Issue by teacherpan** [yunzhiclub/MeasurementItemFrontEnd#1071]
这是由于：一个生产企业生产的每个器具都有一个唯一的编号。
1. 将生产编号由 器具生产信息实体 中删除 ，添加到器具使用信息 实体中。
2.  器具生产信息实体 修改为： 器具生产器具种类 实体。(使用IDEA自带的改名功能）

**Comment by zhuchenshu** [comment]
done
