### ISSUE TITLE
强检-合格统计界面

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#117]
1.将 器具名称字段 移至 主体字段 后面 2.将 年度 字段去掉。注意：合格统计界面 侧重于同一年度，不同区域比较，例如：区域搜索廊坊，主体 应该显示 安次区这些 县级区域3.将区域放置 查询列 第二行第一位 4.将示例数据 年度 改成整个2005年，将示例数据 主体 改成 安次区，固安区等，以保证数据准确性。5.增加 用户 字段

**Comment by liuxiqian** [comment]
@CYYShirley  按照任务 修改界面

**Comment by CYYShirley** [comment]
收到
