### ISSUE TITLE
强检-合格率统计界面

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#118]
将主体 字段去掉，注意：主要侧重于同一区域，不同的年度下的比较。例如：选择区域为廊坊，应当显示廊坊在 不同年份下 的比较。  注意 : 区域要给默认值，默认值为当然用户所在区域。
增加 用户 字段

**Comment by liuxiqian** [comment]
@CYYShirley 参照任务，修改界面

**Comment by CYYShirley** [comment]
收到
