### ISSUE TITLE
根据技术机构获取所有的计量标准装置，并且实现分页

### ISSUE THREAD

**Issue by CYYShirley** [yunzhiclub/MeasurementItemFrontEnd#1198]
pageAllByTechnicalInstitution方法----根据技术机构获取所有标准装置的分页列表

**Comment by teacherpan** [comment]
这个方法有问题。标准管理一览表，针对的用户是管理部门。所以，必然是获取某个部门所辖的所有的标准装置。包括该管理部门所在区域，以及其子区域。

**Comment by teacherpan** [comment]
单一取个某一个技术机构的没有问题。

**Comment by gaoliming123** [comment]
那潘老师，现在是某一个具体技术机构的标准装置还是所有技术机构下的所有标准装置。那还需要根据区域判断吗？

**Comment by teacherpan** [comment]
这个方法不需要。它就是在获取某个技术机构的标准装置。当前登录用户为：技术机构

**Comment by CYYShirley** [comment]
那就把方法名改成pageAllBycurrentUser吧，这样更合适一点儿。

**Comment by teacherpan** [comment]
可以。
