### ISSUE TITLE
将 产品信息-获证产品目录 去掉

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#120]
将 产品信息-获证产品目录 界面 去掉（先将这个 菜单注释 掉，先不要删，以作为参考），并将  菜单-器具产品-生产企业器具产品档案   改成 器具产品-获证产品目录。暂时决定添加年检详情字段。
疑问：用不用添加  年检详情字段 ？

**Comment by liuxiqian** [comment]
@CYYShirley 参照任务，修改界面

**Comment by CYYShirley** [comment]
收到
