### ISSUE TITLE
强检/非强检 综合查询和器具详情查询 合并

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#121]
强检/非强检 综合查询和器具详情查询 合并，并将器具编号作为首选 查询条件，将证书编号 查询去掉。
注意：合并之后 添加 状态 字段。
搜索排列如下：第一行： 器具编号 出场编号 第二行： 状态 用途 第三行： 区域 用户 器具名称 第四行：制造单位  测量范围 准确度等级。
注意：待增加 高级搜索 按钮，最多显示三行。

**Comment by liuxiqian** [comment]
@CYYShirley 查看任务，修改界面

**Comment by CYYShirley** [comment]
收到
