### ISSUE TITLE
index界面 查询条件 每个之间的关系 位置 由李总确定

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#125]

**Comment by teacherpan** [comment]
查询条件的顺序与排列方法。见最近的甲方反馈文档。参考原型修改。

**Comment by liuxiqian** [comment]
收到

**Comment by teacherpan** [comment]
@liuxiqian 时间久远，应该尽快完成。

**Comment by teacherpan** [comment]
@liuxiqian  在做任务太多，拖的时间太久。 
在做的任务，不应该超过2个。你把任务占上了，不能及时完成，还好耽误别人来做这个任务。
完成的时间，不应该超过1天。如果是超过1天的任务，则要对任务进行分解。
比如做任务1预计超过两天。
那么应该将任务1分解为任务2，任务3，然后关闭任务1.

**Comment by liuxiqian** [comment]
强检/非强检 综合查询界面：
主体（区域），用户，器具名称，三级强关联
器具用户和准确度等级，测量范围强关联（未选择器具名称前，准确度等级及测试范围无法选择或不显示）
制造单位和许可证号，出厂编号强关联（同上）
检定单位，检定日期，有效期至，检定结果，示值偏差

**Comment by liuxiqian** [comment]
已按上述关联状态 确定查询条件
