### ISSUE TITLE
加入angular-loading-bar

### ISSUE THREAD

**Issue by myskies** [yunzhiclub/MeasurementItemFrontEnd#132]
加入 https://github.com/chieffancypants/angular-loading-bar，实现将进行数据请求时，在页面中显示loading的效果。
tour中loading的效果即是如此实现的。

然后进一步思索。这个插件是如何利用$http而进行loading显示的。用的是什么技术。

**Comment by liuxiqian** [comment]
收到

**Comment by myskies** [comment]
doing

**Comment by myskies** [comment]
done
