### ISSUE TITLE
配置新模板的路由信息

### ISSUE THREAD

**Issue by myskies** [yunzhiclub/MeasurementItemFrontEnd#135]
@liuxiqian 指导 @CYYShirley 进行新的商业模板的路由信息配置。
步骤如下：
1. 同步项目并切换至template分支，执行npm install   bower install 安装项目依赖
2. 在config.js中，参考 强检器具 -- 分类统计 增加项目的所有路由信息。参考资料：ui-router
3. 编辑view/common/navigation，参考 强检器具 -- 分类统计 增加菜单信息.
4. 由于ui-router中，并没有配置控制器信息，所以需要对涉及到的V层代码逐一添加ng-controller属性。参考：views/strongcheck/Numbercategories/index.html 

模板原始文件位于根目录下的template文件夹。模板原型地址：http://wrapbootstrap.com/preview/WB055J451

**Comment by liuxiqian** [comment]
收到
