### ISSUE TITLE
技术机构考核申请 新增界面

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#145]
@CYYShirley

**Comment by myskies** [comment]
@litian1218 做这个。

**Comment by litian1218** [comment]
收到

**Comment by litian1218** [comment]
字段参考er图？

**Comment by myskies** [comment]
界面参考需求分析。字段找安强

**Comment by litian1218** [comment]
好的

**Comment by litian1218** [comment]
@anqiang1995

**Comment by anqiang1995** [comment]
收到

**Comment by litian1218** [comment]
添加接口：/Business/Technology/getAll
保存接口：/Business/Technology/save

**Comment by liuxiqian** [comment]
接口格式 没有参照之前后台传过来的，参照其他已完成的

**Comment by litian1218** [comment]
技术机构申请 add界面
api:/Business/Technology/save
示例数据：
[{
id:'1',
department_id:'申请单位id',
user_id:'申请人id',
zipcode:'邮编',
phonenumber:'电话',
time:'申请日期',
post_id：‘岗位id’
workflow_type_id:'工作流类型id',
examine_user_id:'下一审核员id',
apply_attachment_id:'1/申请附件id',
}]

**Comment by liuxiqian** [comment]
@litian1218 参照这个修改 https://github.com/yunzhiclub/MeasurementItemFrontEnd/issues/246 注意统一api中url的格式，注意大小写

**Comment by litian1218** [comment]
done
