### ISSUE TITLE
修改合格统计以及合格率统计两个原型

### ISSUE THREAD

**Issue by myskies** [yunzhiclub/MeasurementItemFrontEnd#156]
合格统计，显示同一年度各地区间的差异。
合格率统计，显示同一区域，不同年度的差异。
按上述的思路修改原型。
1.去除合格统计数据列表中的 年度 一列。
2. 去除合格率统计 数据列表中中 主体 一列。

**Comment by liuxiqian** [comment]
潘老师，这个已经修改了
