### ISSUE TITLE
删除按扭，增加 删除 时的确认框。

### ISSUE THREAD

**Issue by teacherpan** [yunzhiclub/MeasurementItemFrontEnd#1620]
1.进行前台的template/full文件夹
2.执行grunt live
3.打开http://localhost:9002/#!/interface/alerts
4. 点击warning查看效果，并找到后台的相关代码。
5. 在项目前台找到删除按钮，增加 删除 确认框。
6. 提示语：该操作不可逆，您确认
7. 参考commomService中的success方法，进行封装。使其它的C层也够方便的使用该警告方法。

**Comment by teacherpan** [comment]
@chuhang123

**Comment by chuhang123** [comment]
收到
