### ISSUE TITLE
标准装置管理：档案管理->查看标准器信息->新增

### ISSUE THREAD

**Issue by zhangjiahao1225** [yunzhiclub/MeasurementItemFrontEnd#1660]
文件位置:views/standard/file/detailadd.html
![image](https://user-images.githubusercontent.com/14845866/28995280-c6cdccd8-7a17-11e7-8dac-b03d94fd28b7.png)

1 将图中单选框进行格式美化，参考https://github.com/yunzhiclub/MeasurementItemFrontEnd/issues/1656
2 添加验证：必须所有的都填上以后才可以保存

**Comment by chenzhigao** [comment]
done
