### ISSUE TITLE
个人中心：form表单验证。用户输入密码不合要求时，提示错误。两次密码不一致时，提示错误

### ISSUE THREAD

**Issue by chuhang123** [yunzhiclub/MeasurementItemFrontEnd#1688]

**Comment by chenzhigao** [comment]
doing

**Comment by teacherpan** [comment]
@chuhang123 将ng-click方式的提交。改为<form ng-submit
然后增加一个隐藏按钮
<ng-show="form.$submitted" disabled>正在处理数据...
当表单提交时，显示正在处理数据按钮
可以参考 强制检定备案中的新增 （user1）

**Comment by chuhang123** [comment]
收到
