### ISSUE TITLE
人员资质管理  改为  人员管理

### ISSUE THREAD

**Issue by CYYShirley** [yunzhiclub/MeasurementItemFrontEnd#1731]
1、人员资质管理名称该为人员管理；
2、暂时去除人员资质查看，去除编号；
3、解决保存内容只有姓名的问题；
4、是否显示市区县部分，参考用户管理 -> 器具用户；
5、菜单中去掉资格证类别管理。

**Comment by teacherpan** [comment]
这个也是，改WebMenuAppDataInit中的菜单名称
