### ISSUE TITLE
后台，数据初始化，去除系统设置的资格证类别管理 去除标准装置管理的授权检定机构查询 

### ISSUE THREAD

**Issue by teacherpan** [yunzhiclub/MeasurementItemFrontEnd#1745]

**Comment by zhangjiahao1225** [comment]
第二个需要做删除的是这个吗？没有找到授权检定机构查询。

**Comment by zhangjiahao1225** [comment]
![image](https://user-images.githubusercontent.com/14845866/29055461-41e4c3cc-7c2f-11e7-9f8b-587d739d13da.png)

**Comment by teacherpan** [comment]
只删除数据初始化中对应的菜单，让前台不显示这两项菜单
