### ISSUE TITLE
强检器具管理：制定检定器具管理

### ISSUE THREAD

**Issue by zhangjiahao1225** [yunzhiclub/MeasurementItemFrontEnd#1762]
1和2  添加按钮样式   3将表头进行比例分配，美化界面

![_20170808203905](https://user-images.githubusercontent.com/14845866/29072251-7fc017ce-7c79-11e7-8649-4c0a83607d15.png)

文件位置：views/mandatory/integrated/index.html

**Comment by chenzhigao** [comment]
doing
