### ISSUE TITLE
add前台界面：非强检器具新增界面——综合查询

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#178]
综合查询optionalIntegrated，增加界面,市region，区县county，器具用户user，器具名称name，状态status，型号规格type，用途purpose，测量范围measureScale，准确度等级rank，制造单位manufactureUnit，出厂编号factoryNum，安装地点fixSite，许可证号licenseNum

**Comment by liuxiqian** [comment]
非强检 综合查询界面 增加字段已完成

**Comment by myskies** [comment]
doing

**Comment by myskies** [comment]
后台,done. 接口地址：/OptionalIntergrated/save
示例数据
`        JSONObject jsonObject = new JSONObject();
        jsonObject.put("region", "唐山市");
        jsonObject.put("county", "乐亭县");
        jsonObject.put("user", "器具用户");
        jsonObject.put("name", "器具名称");
        jsonObject.put("status", "状态");
        jsonObject.put("type", "规格型号");
        jsonObject.put("purpose", "用途");
        jsonObject.put("measureScale", "测试范围");
        jsonObject.put("rank", "准备度等级");
        jsonObject.put("manufactureUnit", "制造单位");
        jsonObject.put("factoryNum", "出厂编号");
        jsonObject.put("fixSite", "安装地点");
        jsonObject.put("licenseNum", "许可证号");`

**Comment by myskies** [comment]
前台doing

**Comment by myskies** [comment]
@CYYShirley 修正一下界面

**Comment by CYYShirley** [comment]
好的

**Comment by liuxiqian** [comment]
done

**Comment by gaoliming123** [comment]
后台done index界面数据
api:/OptionalIntergrated/getAll
示例数据
[{"id":1,
"region":"唐山市",
"county":"乐亭县",
"user":"器具用户",
"name":"器具名称",
"status":"状态",
"purpose":"用途",
"measureScale":"测试范围",
"rank":"准备度等级",
"manufactureUnit":"制造单位",
"factoryNum":"出厂编号",
"fixSite":"安装地点",
"licenseNum":"许可证号"
}]

**Comment by liuxiqian** [comment]
index界面 获取后台数据
