### ISSUE TITLE
add前台界面：标准装置 —— 机构授权检定项目

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#179]
机构授权检定项目standardAuthorization，增加界面市region，区县county，技术机构technical，器具名称name，准确度等级rank，测量范围measureScale，地址address，联系电话phone

**Comment by liuxiqian** [comment]
机构授权检定项目 新增字段已完成

**Comment by gaoliming123** [comment]
前台doing

**Comment by liuxiqian** [comment]
后台接口地址：url未知

**Comment by gaoliming123** [comment]
后台doing

**Comment by gaoliming123** [comment]
后台done .api：/StandardAuthorization/save

**Comment by gaoliming123** [comment]
后台done index界面数据
api:/StandardAuthorization/getAll
示例数据
[{"id":1,
"region":"唐山市",
"county":"乐亭县",
"technical":"技术机构",
"name":"器具名称",
"rank":"准确度等级",
"measureScale":"测量范围",
"address":"地址",
"phone":"联系电话"
}]

**Comment by litian1218** [comment]
doing

**Comment by CYYShirley** [comment]
前台save done

**Comment by liuxiqian** [comment]
index界面 获取后台全部数据

**Comment by CYYShirley** [comment]
doing
