### ISSUE TITLE
add前台界面：标准装置 —— 档案查询

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#180]
档案查询standardFile，增加界面字段：市region，区县county，代码code，计量标准装置名称name，考核证表编号certificateNum，考核日期checkDate，颁发日期issueDate，有效期至validityDate

**Comment by liuxiqian** [comment]
档案查询 新增界面字段待完成，是否增加弹框里面字段

**Comment by myskies** [comment]
弹窗等三个主体。强检，非强检、标准装置三个完成后。再进一步研发。

**Comment by myskies** [comment]
后台doing

**Comment by myskies** [comment]
后台done.接口地址：/StandardFile/save
示例数据:
`        jsonObject.put("region", "唐山市");
        jsonObject.put("county", "乐亭县");
        jsonObject.put("code", "代码");
        jsonObject.put("name", "器具名称");
        jsonObject.put("certificateNum", "考核证表编号");
        jsonObject.put("checkDate", "考核日期");
        jsonObject.put("issueDate", "颁发日期");
        jsonObject.put("validityDate", "有效期至");`

**Comment by liuxiqian** [comment]
前台doing

**Comment by liuxiqian** [comment]
前台done

**Comment by gaoliming123** [comment]
后台done index界面数据
api: /StandardFile/getAll
示例数据
[{"id":1,
"region":"唐山市",
"county":"乐亭县",
"code":"代码",
"name":"器具名称",
"certificateNum":"考核证表编号",
"checkDate":"考核日期",
"issueDate":"颁发日期",
"validityDate":"有效期至"
}]

**Comment by liuxiqian** [comment]
index界面  获取后台全部数据

**Comment by CYYShirley** [comment]
doing
