### ISSUE TITLE
add前台界面：器具产品——器具生产企业档案

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#181]
器具生产企业档案measuringDeviceApplianceArchives，增加界面字段：市region，区县county，企业名称name，企业代码code，学科类别discipline，器具名称dissipativeName，地址address，法人姓名legalName，电话legalPhone，联系人registrantName

**Comment by liuxiqian** [comment]
doing

**Comment by myskies** [comment]
区域（主体）修改为： 市  区县 两个字段。另外，先在GITHUB中，做字段的翻译。翻译后，直接编辑第一条留言。

**Comment by liuxiqian** [comment]
添加完字段

**Comment by myskies** [comment]
@张佳豪 按上面的字段名称，新建分支，并建立实体类（两个文件）及实体类对应的测试文件。单元测试中，成功添加数据后，进行pull request.

**Comment by myskies** [comment]
@liuxiqian  为这个 器具生产企业档案 起个英文名，方便前后台统一命名。

**Comment by liuxiqian** [comment]
已添加完器具生产企业档案英文名

**Comment by myskies** [comment]
@CYYShirley 前台界面任务领走。

**Comment by myskies** [comment]
步骤。1.找到对应的controller  -- MeasuringdeviceAppliancearchivesAddCtrl.
2.注释掉controller中的所有的方法。

3.找到对应的view 
4.将所有的input中的id删除，form上的id也删除。
5. 在C层中，初始化数据
`     
   $scope.data = {
        	字段名1:'',
	        字段名2:''
        	
        };
`

6. 对应view中的input全部使用ng-model进行绑定。比如ng-model='data. county'
7.在view中，增加`{{data}}`实时查看绑定结果 。
8. 以上任务完成后，及时反馈。不明白的直接留言。

**Comment by CYYShirley** [comment]
收到

**Comment by liuxiqian** [comment]
后台接口地址：url未知

**Comment by gaoliming123** [comment]
后台doing

**Comment by gaoliming123** [comment]
后台done .接口地址：/MeasuringdeviceApplianceArchive/save
示例数据：
JSONObject jsonObject = new JSONObject();
        jsonObject.put("region", "唐山市");
        jsonObject.put("county", "乐亭县");
        jsonObject.put("name", "企业名称");
        jsonObject.put("code", "代码");
        jsonObject.put("discipline", "学科类别");
        jsonObject.put("dissipativeName", "器具名称");
        jsonObject.put("address", "地址");
        jsonObject.put("legalName", "法人姓名");
        jsonObject.put("legalPhone", "电话");
        jsonObject.put("registrantName", "联系人");

**Comment by gaoliming123** [comment]
后台done index界面数据
api: /MeasuringdeviceApplianceArchive/getAll
示例数据(数组对象)：
[{"id":1,
"region":"唐山市",
"country":null,
"name":"企业名称",
"code":"代码",
"discipline":"学科类别",
"dissipativeName":"器具名称",
"address":"地址",
"legalName":"法人姓名",
"legalPhone":"电话",
"registrantName":"联系人"
}]

**Comment by litian1218** [comment]
doing

**Comment by litian1218** [comment]
前台save done

**Comment by liuxiqian** [comment]
index界面 获取后台全部数据

**Comment by litian1218** [comment]
doing
