### ISSUE TITLE
add前台界面：器具产品——获证产品目录

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#182]
获证产品目录CertifiedProduct，增加界面字段,市region，区县county,器具名称name,准确度等级rank,测量范围measureScale,制造单位manufactureUnit,许可证号licenseNum,发证日期issueDate,有效期至validityDate

**Comment by liuxiqian** [comment]
添加获证产品目录 增加界面字段 完成

**Comment by myskies** [comment]
@litian1218 要求同上一个。完成后及时pull request

**Comment by litian1218** [comment]
收到

**Comment by myskies** [comment]
后台doing

**Comment by myskies** [comment]
后台done

**Comment by gaoliming123** [comment]
后台done index界面数据
api:/CertifiedProduct/getAll
返回示例数据(对象数组)：
[{
    "id":1,"region":"唐山市",
    "county":"乐亭县",
    "name":"器具名称",
    "rank":"准备度等级",
    "measureScale":"测试范围",
    "manufactureUnit":"制造单位",
    "licenseNum":"许可证号",
    "issueDate":"发证日期",
    "validityDate":"有效期至"
}]

**Comment by litian1218** [comment]
doing

**Comment by litian1218** [comment]
前台save done

**Comment by liuxiqian** [comment]
index界面 获取后台全部数据
