### ISSUE TITLE
add前台界面：人员资质管理—— 综合查询

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#183]
综合查询personnelPersonnelFile，增加界面字段：市region，区县county，技术机构technical，建标用户user，生产企业generative，姓名name，年龄age，学历edubg，职称title，从业年限occupation，资格证qualifierCertificate，授权项目authorizeItem，发证单位issueUnit，发证日期issueTime，有效期至validityTime

**Comment by liuxiqian** [comment]
人员资质管理-综合查询添加界面 字段 已完成

**Comment by liuxiqian** [comment]
前台doing

**Comment by gaoliming123** [comment]
前台doing

**Comment by liuxiqian** [comment]
后台接口地址：url未知

**Comment by gaoliming123** [comment]
后台done .接口地址：/PersonalFile/save
示例数据：
JSONObject jsonObject = new JSONObject();
        jsonObject.put("region", "唐山市");
        jsonObject.put("county", "乐亭县");
        jsonObject.put("technical", "技术机构");
        jsonObject.put("user", "建标用户");
        jsonObject.put("generative", "generative");
        jsonObject.put("name", "姓名");
        jsonObject.put("age", "年龄");
        jsonObject.put("edubg", "学历");
        jsonObject.put("title", "职称");
        jsonObject.put("occupation", "从业年限");
        jsonObject.put("qualifierCertificate", "资格证");
        jsonObject.put("authorizeItem", "授权项目");
        jsonObject.put("issueUnit", "发证单位");
        jsonObject.put("issueTime", "发证日期");
        jsonObject.put("validityTime", "有效期至");

**Comment by gaoliming123** [comment]
后台done(获取后台index界面数据)
api:/PersonalFile/getAll
示例数据
[
{"id":1,"region":null,"county":null,"technical":"崇化所","user":"卢卡斯","generative":"富士康","name":"张楠","age":"29","edubg":"***","title":"***","occupation":"3年","qualifierCertificate":"检定员证","authorizItem":"加油机","issueUnit":"发证单位1","issueTime":"2016.03.03","validityTime":"2017.12.31"},
{"id":2,"region":"唐山市","county":"乐亭县","technical":"123","user":"132","generative":"generative","name":"姓名","age":"age","edubg":"学历","title":"职称","occupation":"从业年限","qualifierCertificate":"资格证","authorizItem":null,"issueUnit":"发证单位","issueTime":"发证日期","validityTime":"有效期至"}
]

**Comment by litian1218** [comment]
doing

**Comment by litian1218** [comment]
前台save done

**Comment by liuxiqian** [comment]
index界面 获取后台全部数据

**Comment by myskies** [comment]
@liuxiqian 关闭此讨论点。重新建立新的讨论点。
