### ISSUE TITLE
区域指令yunzhiDistrictName有报错

### ISSUE THREAD

**Issue by CYYShirley** [yunzhiclub/MeasurementItemFrontEnd#1835]
![11](https://user-images.githubusercontent.com/23068558/29160790-3b5a47f8-7de6-11e7-94f1-2e0dc472c17b.png)

**Comment by CYYShirley** [comment]
强检器具综合查询页面的高级搜索不能点击

**Comment by teacherpan** [comment]
@CYYShirley  这个问题描述的很好
