### ISSUE TITLE
admin用户登录以后，“系统设置--用户管理”中不能进行用户删除和用户密码重置。

### ISSUE THREAD

**Issue by CYYShirley** [yunzhiclub/MeasurementItemFrontEnd#1980]
1、删除按钮点击以后没有反应；
2、密码重置按钮点击以后显示“系统或网络异常”，如下图所示报错
![1](https://user-images.githubusercontent.com/23068558/29393547-f285ec98-8336-11e7-99f6-28739a964fb8.png)

**Comment by teacherpan** [comment]
@chuhang123  优先lable为 error的问题

**Comment by chuhang123** [comment]
收到
