### ISSUE TITLE
用户注册的时候如果先后两个用户名相同,那么在注册的时候前台并未给出该用户名是否已被注册的信息，并且点击注册以后失去反应。

### ISSUE THREAD

**Issue by zhangjiahao1225** [yunzhiclub/MeasurementItemFrontEnd#1986]

**Comment by chuhang123** [comment]
doing

**Comment by chuhang123** [comment]
![image](https://user-images.githubusercontent.com/16712674/29397994-722c19b4-8354-11e7-9f14-e080f9aea4be.png)

**Comment by teacherpan** [comment]
@zhangjiahao1225 pull最新的代码，测试。正常后，关闭此issue

**Comment by zhangjiahao1225** [comment]
已经从最新的同步下来了，但是我这里好像没有变化

**Comment by teacherpan** [comment]
@chuhang123 pull下来，确认一下。给出GIF动图

**Comment by chuhang123** [comment]
收到
