### ISSUE TITLE
每注册一次，在进行注册的时候第一栏请选择那里就会多出来一个请选择字段

### ISSUE THREAD

**Issue by zhangjiahao1225** [yunzhiclub/MeasurementItemFrontEnd#1987]

**Comment by teacherpan** [comment]
@zhangjiahao1225 给出对应的截图，将使其它成员更明白问题在哪

**Comment by zhangjiahao1225** [comment]
![image](https://user-images.githubusercontent.com/14845866/29407067-a2528580-8375-11e7-9613-4e3d8ad84fbf.png)

**Comment by teacherpan** [comment]
这个问题主要是地址引用的问题。第一次由A中抓取了一个数组，添加了一个请选择。第二次再由A中抓取这个数组，再添加一个请选择。但由于是地址引用，在第一次添加请选择时，A中的数组中同时也被添加了一个请选择，所以第二次由A中抓取时，请选择已经被添加了。
