### ISSUE TITLE
admin登录后，“系统设置 - 强检器具类别管理”及“系统设置--标准器类别管理”中可选精度字段显示需要优化。

### ISSUE THREAD

**Issue by CYYShirley** [yunzhiclub/MeasurementItemFrontEnd#1991]
![1](https://user-images.githubusercontent.com/23068558/29395694-519a6264-8345-11e7-8122-466677aeb5e3.png)
可选精度字段，每两个精度之间加空格使区分明显。

**Comment by chuhang123** [comment]
doing
