### ISSUE TITLE
admin登录后 系统设置的角色管理里面的删除是不是应该去掉

### ISSUE THREAD

**Issue by zhangjiahao1225** [yunzhiclub/MeasurementItemFrontEnd#1995]

**Comment by zhangjiahao1225** [comment]
![image](https://user-images.githubusercontent.com/14845866/29410887-300701c6-8385-11e7-8c88-3f9acd18fd39.png)

**Comment by teacherpan** [comment]
系统管理员的使用背景是我们这样，从完善的角度上来讲，是应该隐藏。就这样吧。不改了这个。
