### ISSUE TITLE
系统设置 菜单管理的各个菜单的权重是不是应该加一个过滤器

### ISSUE THREAD

**Issue by zhangjiahao1225** [yunzhiclub/MeasurementItemFrontEnd#1996]

**Comment by zhangjiahao1225** [comment]
![image](https://user-images.githubusercontent.com/14845866/29410846-0c492b1a-8385-11e7-944d-454589491199.png)

**Comment by teacherpan** [comment]
系统菜单在这只是查看功能。可有可无。这是前期想进行定制的产物。有就这么放着吧。有BUG也不用修复。
