### ISSUE TITLE
个人中心 修改密码成功后一直显示数据正在处理

### ISSUE THREAD

**Issue by zhangjiahao1225** [yunzhiclub/MeasurementItemFrontEnd#1997]
![image](https://user-images.githubusercontent.com/14845866/29411448-6d83de6e-8387-11e7-8bf2-af7fc23f6f45.png)

**Comment by zhangjiahao1225** [comment]
如果输错原密码，提示密码不正确以后也是一直数据正在处理，不进行跳转

**Comment by teacherpan** [comment]
@chuhang123  原密码错误后，除了提示以外，还要设置form.$submitted=false

**Comment by chuhang123** [comment]
收到
