### ISSUE TITLE
“人员管理--档案管理”中，新增的人员数据中，从业年限是否应该加一个提示不能为负数。

### ISSUE THREAD

**Issue by CYYShirley** [yunzhiclub/MeasurementItemFrontEnd#1998]
![qq 20170817200857](https://user-images.githubusercontent.com/23068558/29411531-d673d348-8387-11e7-9aef-02bb336e7f78.png)

**Comment by teacherpan** [comment]
从业年限。应该是填写“从业开始日期”后，系统计算出来的。如果不是，那么这个做的有问题。从业年限应该随着时间的推移自动更新。当前，也不能为负数 。

**Comment by teacherpan** [comment]
@CYYShirley  前台添加表单中，去除从业年限字段，增加首次从业时间字段。index列表中，增加首次从业时间字段。
@zhangjiahao1225 后在从业年限字段上加入“不对应数据表字段”的注解。在 get从业年限（）的方法中，取出当前日期 ，然后减去首次从业年限，最后返回一个计算后的 从业年限。
在实体中，增加 首次从业时间 字段。
