### ISSUE TITLE
系统设置 - 器具种类添加中，可选精确度增加删除。

### ISSUE THREAD

**Issue by chenzhigao** [yunzhiclub/MeasurementItemFrontEnd#2010]
![qq 20170819095819](https://user-images.githubusercontent.com/29062075/29482520-fde32cce-84c4-11e7-9f0d-666b4adcd6dc.png)

**Comment by teacherpan** [comment]
1. 增加删除按钮。
2. 增加实体的软件删除
参考 ： https://www.thoughts-on-java.org/implement-soft-delete-hibernate/
