### ISSUE TITLE
强检器具备案管理 测试增加，编辑，删除功能

### ISSUE THREAD

**Issue by gaoliming123** [yunzhiclub/MeasurementItemFrontEnd#2077]
前提：器具用户登录,例如:user1:user1。强检器具类别已经有数据,参照https://github.com/yunzhiclub/MeasurementItemFrontEnd/issues/2075
![_004](https://user-images.githubusercontent.com/19948248/29602244-e9388daa-8811-11e7-86e8-2e9bceaf113a.png)

**Comment by gaoliming123** [comment]
![peek 2017-08-23 15-02](https://user-images.githubusercontent.com/19948248/29602760-1a08f210-8814-11e7-950c-fd9907ebd338.gif)

**Comment by chuhang123** [comment]
编辑时发现bug，已建立issue，https://github.com/yunzhiclub/MeasurementItemFrontEnd/issues/2084
