### ISSUE TITLE
人员资质 -》 档案管理  增删改

### ISSUE THREAD

**Issue by gaoliming123** [yunzhiclub/MeasurementItemFrontEnd#2083]
登录用户为 技术机构  例如:user3:user3
![_006](https://user-images.githubusercontent.com/19948248/29605391-3fb285c2-881d-11e7-96e6-946e7cbcd3b6.png)

**Comment by chuhang123** [comment]
经测试，发现两个小bug，https://github.com/yunzhiclub/MeasurementItemFrontEnd/issues/2087     https://github.com/yunzhiclub/MeasurementItemFrontEnd/issues/2085

**Comment by chenzhigao** [comment]
经测试未发现bug
