### ISSUE TITLE
强检器具管理-- 指定器具管理      计划检定日期算法有问题

### ISSUE THREAD

**Issue by chuhang123** [yunzhiclub/MeasurementItemFrontEnd#2092]
![image](https://user-images.githubusercontent.com/16712674/29609278-3c9907c4-8829-11e7-98a4-b32e45309dc6.png)
![image](https://user-images.githubusercontent.com/16712674/29609304-53e22028-8829-11e7-917d-673c7405f3da.png)

**Comment by teacherpan** [comment]
@chuhang123  这个没有问题。如果还没有检定记录，那么首次检定日期即：计划检定日期。
如果有检定记录，则计划检定日期 = 最近一次的检定日期 + 检定周期。
请确认。

**Comment by chuhang123** [comment]
收到
