### ISSUE TITLE
index前台界面:标准装置 —— 机构授权检定项目

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#244]
后台done index界面数据
api:/StandardAuthorization/getAll
示例数据
[{"id":1,
"region":"唐山市",
"county":"乐亭县",
"technical":"技术机构",
"name":"器具名称",
"rank":"准确度等级",
"measureScale":"测量范围",
"address":"地址",
"phone":"联系电话"
}]

**Comment by liuxiqian** [comment]
@CYYShirley 修改此界面

**Comment by CYYShirley** [comment]
收到

**Comment by CYYShirley** [comment]
前台done

**Comment by CYYShirley** [comment]
前台done
