### ISSUE TITLE
index前台界面：器具产品——器具生产企业档案

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#245]
后台done index界面数据
api: /MeasuringdeviceApplianceArchive/getAll
示例数据(数组对象)：
[{"id":1,
"region":"唐山市",
"country":null,
"name":"企业名称",
"code":"代码",
"discipline":"学科类别",
"dissipativeName":"器具名称",
"address":"地址",
"legalName":"法人姓名",
"legalPhone":"电话",
"registrantName":"联系人"
}]

**Comment by liuxiqian** [comment]
index界面 获取后台全部数据

**Comment by liuxiqian** [comment]
@litian1218 迁移至此issue，修改此界面

**Comment by litian1218** [comment]
doing

**Comment by litian1218** [comment]
done

**Comment by CYYShirley** [comment]
前台done
