### ISSUE TITLE
index前台界面：器具产品——获证产品目录

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#246]
后台done index界面数据
api:/CertifiedProduct/getAll
返回示例数据(对象数组)：
[{
"id":1,"region":"唐山市",
"county":"乐亭县",
"name":"器具名称",
"rank":"准备度等级",
"measureScale":"测试范围",
"manufactureUnit":"制造单位",
"licenseNum":"许可证号",
"issueDate":"发证日期",
"validityDate":"有效期至"
}]

**Comment by liuxiqian** [comment]
index界面获取后台数据

**Comment by CYYShirley** [comment]
doing

**Comment by CYYShirley** [comment]
前台done
