### ISSUE TITLE
index前台界面：人员资质管理—— 综合查询 

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#247]
后台done(获取后台index界面数据)
api:/PersonalFile/getAll
示例数据
[
{"id":1,"region":null,"county":null,"technical":"崇化所","user":"卢卡斯","generative":"富士康","name":"张楠","age":"29","edubg":"***","title":"***","occupation":"3年","qualifierCertificate":"检定员证","authorizItem":"加油机","issueUnit":"发证单位1","issueTime":"2016.03.03","validityTime":"2017.12.31"},
{"id":2,"region":"唐山市","county":"乐亭县","technical":"123","user":"132","generative":"generative","name":"姓名","age":"age","edubg":"学历","title":"职称","occupation":"从业年限","qualifierCertificate":"资格证","authorizItem":null,"issueUnit":"发证单位","issueTime":"发证日期","validityTime":"有效期至"}
]

**Comment by liuxiqian** [comment]
index界面 获取后台数据

**Comment by litian1218** [comment]
doing

**Comment by myskies** [comment]
上一条信息反馈于3天前。及时反馈状态。

**Comment by litian1218** [comment]
这个已经写完了，忘记pull没，检查之后反馈结果

**Comment by litian1218** [comment]
将easyUI去除转换为模板自带table doing

**Comment by litian1218** [comment]
迁移至#305
