### ISSUE TITLE
index前台界面：标准装置 —— 档案查询 

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#250]
后台done index界面数据
api: /StandardFile/getAll
示例数据
[{"id":1,
"region":"唐山市",
"county":"乐亭县",
"code":"代码",
"name":"器具名称",
"certificateNum":"考核证表编号",
"checkDate":"考核日期",
"issueDate":"颁发日期",
"validityDate":"有效期至"
}]

**Comment by liuxiqian** [comment]
index界面 获取后台全部数据

**Comment by liuxiqian** [comment]
doing

**Comment by liuxiqian** [comment]
@CYYShirley 参照我刚修改的界面，修改此界面

**Comment by CYYShirley** [comment]
好的

**Comment by CYYShirley** [comment]
前台done
