### ISSUE TITLE
非强检器具鉴定信息实体

### ISSUE THREAD

**Issue by gaoliming123** [yunzhiclub/MeasurementItemFrontEnd#256]
字段
器具编号:applianceNum
证书编号:certificateNum
示值偏差:indicationDeviation
检定日期:checkTime
检定单位:checkUnit
检定结果:checkResult
有效期至:validityTime
检定员:checker
核验员:examiner

**Comment by myskies** [comment]
修改器具编号 为：非强检器具表名+Id ,并做为非强检器具的外键。关键为ManyToOne.
@zhangjiahao1225

**Comment by zhangjiahao1225** [comment]
doing

**Comment by zhangjiahao1225** [comment]
done
