### ISSUE TITLE
标准装置检定信息实体

### ISSUE THREAD

**Issue by gaoliming123** [yunzhiclub/MeasurementItemFrontEnd#258]
器具编号:applianceNum
检定日期checkTime
检定单位:checkUnit
检定结果:checkResult
证书编号:certificateNum
有效期至:validityTime
检定员:checker
核验员:examiner
修正值:correctValue

**Comment by myskies** [comment]
器具编号 应该是: 器具表名+Id

**Comment by gaoliming123** [comment]
后台doing

**Comment by gaoliming123** [comment]
done
