### ISSUE TITLE
前台引用travis grunt test 自动化测试。

### ISSUE THREAD

**Issue by myskies** [yunzhiclub/MeasurementItemFrontEnd#268]
前台的问题较多，引入后，将面临大量的完善代码的操作。
@liuxiqian  做好大量修正前台代码的准备。

**Comment by liuxiqian** [comment]
收到

**Comment by myskies** [comment]
done. @liuxiqian  基于最新的开发分支，新建分支。执行grunt test 修正反馈的BUG信息
