### ISSUE TITLE
标准器后台实体

### ISSUE THREAD

**Issue by gaoliming123** [yunzhiclub/MeasurementItemFrontEnd#277]
字段
standardFileId: 标准装置id    //外健
name:名称
code:代码
makeUnit:制造单位
factoryNum:出场编号
licenseNum:许可证号
type:型号规格
rank:准确度等级
mesureScale:测量范围
subject:学科类别

**Comment by gaoliming123** [comment]
后台doing

**Comment by gaoliming123** [comment]
后台done
api:/StandardDevice/save

**Comment by myskies** [comment]
@gaoliming123 完成后，及时关闭讨论点。
