### ISSUE TITLE
前台service层统一命名为 所做页面的控制器名+service

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#279]
注:例如，非强检-综合查询的index和add界面相对应的service层为 OptionalIntegratedService
注意命名格式。

**Comment by liuxiqian** [comment]
@CYYShirley @litian1218

**Comment by CYYShirley** [comment]
收到

**Comment by litian1218** [comment]
OK

**Comment by teacherpan** [comment]
任务太粗。分解困难。关闭。以后这种任务，应该在project中，建立一个tab。然后在tab中，一个个将note写进去。
