### ISSUE TITLE
在ER图中，增加WebAppMenu 前台菜单实体。

### ISSUE THREAD

**Issue by teacherpan** [yunzhiclub/MeasurementItemFrontEnd#420]
menu用于设置用户与后台路由信息的权限。 WebAppMenu用于设置前台用户拥有的菜单权限及生成前台的菜单树。

**Comment by teacherpan** [comment]
@anqiang1995 修改下ER图关于菜单配置这块。 用户：角色 = n:n 角色：前台菜单 = n:n   前台菜单：后台菜单 = n:n

**Comment by anqiang1995** [comment]
收到
