### ISSUE TITLE
制作 角色管理  界面

### ISSUE THREAD

**Issue by anqiang1995** [yunzhiclub/MeasurementItemFrontEnd#479]
角色管理  界面需要有显示列表，按钮 有 添加角色 、编辑角色、角色详情，在角色的添加，编辑、详情页面需要以下内容：1.角色名称 2.菜单列表。

**Comment by CYYShirley** [comment]
doing

**Comment by teacherpan** [comment]
@CYYShirley 可以直接点击右侧的 assign yourself 
![qq 20170522204025](https://cloud.githubusercontent.com/assets/12424383/26309124/64b0ba02-3f2e-11e7-9800-6fd822a1d329.png)

**Comment by CYYShirley** [comment]
好的~
