### ISSUE TITLE
制作 用户管理  界面

### ISSUE THREAD

**Issue by anqiang1995** [yunzhiclub/MeasurementItemFrontEnd#484]
目前前台界面中的 用户管理 管理的是部门需要制作的的  用户管理  指的是管理登录系统的真实的人。用户管理 界面需要有显示列表，按钮 有 添加用户 、编辑用户、用户详情、搜索，搜索框按姓名搜索。区域，部门，岗位，角色搜索此为select框，在用户的列表、添加，编辑、详情页面需要以下内容：用户的用户名、密码、姓名、区域、部门、岗位。

**Comment by anqiang1995** [comment]
用户user

**Comment by liuxiqian** [comment]
doing

**Comment by liuxiqian** [comment]
收到
