### ISSUE TITLE
制作  申请类型管理 界面

### ISSUE THREAD

**Issue by anqiang1995** [yunzhiclub/MeasurementItemFrontEnd#487]
申请类型管理界面需要有显示列表，按钮 有 添加申请类型、编辑申请类型、申请类型详情，在申请类型的编辑、详情页面需要以下内容：1.申请类型名称 2.对应的工作流列表，添加申请类型时，可以输入申请类型名称并选择已存在工作流类型。

**Comment by anqiang1995** [comment]
申请类型applyType

**Comment by teacherpan** [comment]
系统将直接在数据库中添加，不需要界面同。
