### ISSUE TITLE
制作 工作流类型管理  界面

### ISSUE THREAD

**Issue by anqiang1995** [yunzhiclub/MeasurementItemFrontEnd#488]
工作流类型管理 界面需要显示列表，按钮有 添加、删除、编辑。添加、编辑界面应有工作流类型名称、区域类型、部门类型、岗位，用来添加、编辑盖工作流类型所对应的工作流节点。

**Comment by anqiang1995** [comment]
工作流类型workflowType

**Comment by litian1218** [comment]
doing

**Comment by litian1218** [comment]
工作流类型管理：workflowTypeManagement
index界面显示内容：
序号：$index
工作流类型名称：name
区域类型：regionType（用district和指令重名，修改service时总造成联动）
部门类型：departmentType
岗位：post
@anqiang1995 看一下这个是不是符合需求

**Comment by anqiang1995** [comment]
index页面就显示1.序号2.工作流类型名称。

区域类型，部门类型，岗位是对节点进行定义的，当添加、编辑工作流类型时，会选择多个节点，而这多个节点是由 区域类型、部门类型、岗位  决定的。

**Comment by litian1218** [comment]
编辑中区域 部门 岗位 都是select 名称自己填

**Comment by anqiang1995** [comment]
对，应该是区域类型、部门类型。

**Comment by litian1218** [comment]
那select就先写静态页面，以后再改成动态获取？

**Comment by anqiang1995** [comment]
好的，可以
