### ISSUE TITLE
制作  我的工作 中 工作详情  界面

### ISSUE THREAD

**Issue by anqiang1995** [yunzhiclub/MeasurementItemFrontEnd#490]
点击每一条工作进入新的页面，可以查看该项工作的详情信息，详情信息除了有列表页中的信息还应有  上一用户姓名、上一用户联系电话、上一用户提交工作时间、申请人申请时间、附件列表。

**Comment by anqiang1995** [comment]
工作详情页面增加三个按钮，同意、退回申请人、搁置。

**Comment by anqiang1995** [comment]
工作详情workDetail

**Comment by teacherpan** [comment]
我的工作。最新的甲方要求中，不需要。后期将在申请及申请回复中体现。
