### ISSUE TITLE
在project的后台中，每个数据表建立一个note。内容是加入RepositoryRestResource 注解

### ISSUE THREAD

**Issue by teacherpan** [yunzhiclub/MeasurementItemFrontEnd#639]
@gaoliming123 做示例  @zhangjiahao1225  按示例，按ER图，将剩余的实体加入note.

**Comment by teacherpan** [comment]
![image](https://cloud.githubusercontent.com/assets/12424383/26615986/d8529248-45fd-11e7-8085-e3ca833a3b8b.png)

**Comment by zhangjiahao1225** [comment]
好的

**Comment by gaoliming123** [comment]
收到

**Comment by teacherpan** [comment]
放弃。
