### ISSUE TITLE
CheckResultRepository加@repositoryrestsource注解并单元测试:

### ISSUE THREAD

**Issue by gaoliming123** [yunzhiclub/MeasurementItemFrontEnd#649]

**Comment by teacherpan** [comment]
@gaoliming123 增加关联数据的习惯与我们不一致。放弃使用该注解。参考 ：https://stackoverflow.com/questions/23767233/spring-data-rest-post-new-entity-with-relationships
<img width="603" alt="default" src="https://cloud.githubusercontent.com/assets/12424383/26671995/11d96d2e-46ea-11e7-9439-4f7a1b2e8238.png">
