### ISSUE TITLE
毕设：隐藏菜单并修改部分二级菜单名称

### ISSUE THREAD

**Issue by zhangjiahao1225** [yunzhiclub/MeasurementItemFrontEnd#669]
基于zjhbs分支
一级菜单保留： 强制检定管理、非强制检定管理、技术机构管理
二级菜单中：1 强制检定管理保留：强制检定计量器具用户档案 -> 分类统计
                                                          用户强制检定计量器具档案-> 综合查询
                                                          强制检定计量器具合格率统计->合格率统计
                                                          强制检定计量器具年检定量统计->合格统计
                      2 非强制检定管理保留： 非强检检定工作计量器具档案->分主体统计
                                                              非强制检定工作计量器具查询->综合查询
                      3技术机构管理保留：技术机构授权检定项目一览表->机构授权检定项目
                                                         技术机构计量标准装置->档案查询

**Comment by teacherpan** [comment]
@liuxiqian 在data文件夹中，建立一个Menu文件夹。然后给个getAll.json.这个文件中。写入二维数组。第一组数据，一级菜单；一级菜单中有_children字段。该字段中存该一级菜单的二级菜单。

**Comment by teacherpan** [comment]
数组中的对象属性参考ER图中的 前台菜单，看自己需要哪个。 最后，我们按getAll.json中存的数据，自动生成菜单项。这样。想切菜单的话，就简单到直接修改getAll.json这个文件就可以了。

**Comment by liuxiqian** [comment]
收到

**Comment by liuxiqian** [comment]
doing

**Comment by liuxiqian** [comment]
动态获取菜单数据已完成，待解决菜单树第二次加载闪动的问题，已迁移至#756。
