### ISSUE TITLE
学科类别指令的后台数据对接

### ISSUE THREAD

**Issue by teacherpan** [yunzhiclub/MeasurementItemFrontEnd#890]
如数据表中没有学科类别初始化数据，则先进行数据初始化。
按weight进行排序后，输出列表，供前台学科类别指令使用。前台成功对接后，删除app/data目录中，对应的文件夹。

**Comment by teacherpan** [comment]
@CYYShirley @zhangjiahao1225  做第一个指令的数据对接

**Comment by CYYShirley** [comment]
收到

**Comment by liuxiqian** [comment]
前台需要的数据格式：[
    {
        "id": 0,
        "name": "请选择",
        "pingyin": "qingxuanze" 
    },
    {
        "id": 1,
        "name": "几何量",
        "pingyin": "jiheliang"
    },
    {
        "id": 2,
        "name": "化学",
        "pingyin": "huaxue"
    },
    {
        "id": 3,
        "name": "温度",
        "pingyin": "wendu"
    },
    {
        "id": 4,
        "name": "力学",
        "pingyin": "lixue"
    }
]
需要的数据来源：计量器具管理—计量器具生产企业档案，新增 的学科类别

**Comment by teacherpan** [comment]
1. id:0 后台给不了。因为数据表中不在。
2 上面的示例数据指:最少要上面三个属性id name pinyin，后台实际返回的可以多出其它属性，但不能少。
3 拉取最新的代码。器具类别已经进行了初始化。

**Comment by zhangjiahao1225** [comment]
后台工作已完成  对接地址https://yunzhiclub.github.io/MeasurementItemFrontEnd/index.html#_discipline_getall
