### ISSUE TITLE
区域指令 从后台获取数据

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#916]
数据格式：
[
  {
    "id": 1,
    "type": "city",
    "name": "廊坊市",
    "pinyin": "langfangshi"
  },
  {
    "id": 2,
    "type": "district",
    "name": "廊坊市--安次区",
    "pinyin": "anciqu"
  },
  {
    "id": 3,
    "type": "district",
    "name": "廊坊市--广阳区",
    "pinyin": "guangyangqu"
  }
]
数据来源：区域管理的 所有区域

**Comment by liuxiqian** [comment]
上面的示例数据指:最少要上面三个属性id type name pinyin，后台实际返回的可以多出其它属性，但不能少。

**Comment by teacherpan** [comment]
doing: 为该指令增加配置信息。分别取出：1.当前用户所有区域及其子区域信息。2.所有的区域信息. 按不出的配置进行，分别取出数据。
