### ISSUE TITLE
器具用户指令中 器具用户  从后台获取数据

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#919]
修改为：
描述：获取某区域下的所有器具用户实体列表
---
数据请求：
方法：`get`
参数`districtId`(区域ID）
---

数据返回:
```
[
{
"id": 1,
"name": "器具用户一",
"pinyin": "yi"
},
{
"id": 2,
"name": "器具用户二",
"pinyin": "er"
},
{
"id": 3,
"name": "器具用户三",
"pinyin": "san"
},
{
"id": 4,
"name": "器具用户四",
"pinyin": "si"
}
]
```

**Comment by liuxiqian** [comment]
因为 器具用户和 区域相关联，所以需要后台 在部门表 里面取 外键区域id 来关联区域 和 器具用户

**Comment by liuxiqian** [comment]
上面的示例数据指:最少要上面三个属性id  name pinyin，后台实际返回的可以多出其它属性，但不能少。

**Comment by teacherpan** [comment]
@liuxiqian  
> 需要后台在取数据的时候进行判断其部门类型
这个判断，是前台传的，还是后台自动判断当前登录用户的？

**Comment by liuxiqian** [comment]
潘老师，我上面的这个意思是 后台自动判断，因为我看的ER图，没有理解到 怎么样来 前台传部门类型。

**Comment by teacherpan** [comment]
你前台在哪用的，截个图上来。正来来讲。器具用户列表中，怎么会有技术机构的事呢？如果需要自动判断。那么描述中，需要增加：获取 **当前用户** xxxx

**Comment by liuxiqian** [comment]
潘老师，现在不是器具用户和 技术机构公用一个指令吗，那现在是要 我现在写的在 前台用路由判断的 来取值，后台就不需要来判断 部门类型了是吗，  我不知道在前台直接用路由来判断是否严禁。

**Comment by teacherpan** [comment]
前台共用一个指令没问题。但后台并不知道关于前台指令的任何信息，所以也不会替你自动判断，进而给你响应。前后台分离，就是假设后台并不知道你前台发生了什么。
当然了，你用判断路由的方法来配置指令，也是不对的。这样指令不具有通用性。正确的方法是：应该在C层中，给指令传值，然后在指令中，判断传入的值，进行达到配置指令的目的。
指令配置完成后，再按不同的情况，调用不同的后台API。
所以，如果是这种情况，那么你应该建立多个  issue，然后分别给出自己想要的确切的信息。
后台也会给你两个API供你在前台调用。
