### ISSUE TITLE
器具指令 根据 器具用户 从后台获取数据

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#920]
修改为：
描述：获取某器具用户下的所有器具实体列表
---
数据请求：
方法：`get`
参数`measurementUserId`(器具用户ID）
---

数据返回:
```
[
  {
    "id": 1,
    "name": "三角板",
    "pinyin": "sanjiaoban"
  },
  {
    "id": 2,
    "name": "量角器",
    "pinyin": "liangjiaoqi"
  },
  {
    "id": 3,
    "name": "圆规",
    "pinyin": "yuangui"
  }
]
```

**Comment by liuxiqian** [comment]
上面的示例数据指:最少要上面三个属性id name pinyin，后台实际返回的可以多出其它属性，但不能少。

**Comment by liuxiqian** [comment]
上面的示例数据指:最少要上面三个属性id name pinyin，后台实际返回的可以多出其它属性，但不能少。

**Comment by teacherpan** [comment]
@liuxiqian 这个也是一样。你不能只给出想要的数据是什么。还要给出，你可以给后台什么数据，数据格式是什么，又都分别代表什么。
和后台给我们提供API一样。需要给出1：传入数据是什么。2.回传数据是什么。
最后还是回归到了程序的本质问题：
1. 输入数据是什么
2. 期待的输出数据是什么。
