### ISSUE TITLE
器具用户指令 中技术机构 从后台获取数据

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#930]
数据格式
[
    {
        "id": 1,
        "name": "技术机构一",
        "pinyin": "yi"
    },
    {
        "id": 2,
        "name": "技术机构二",
        "pinyin": "er"
    },
    {
        "id": 3,
        "name": "技术机构三",
        "pinyin": "san"
    },
    {
        "id": 4,
        "name": "技术机构四",
        "pinyin": "si"
    }
]
数据来源：部门里面 技术机构的数据

**Comment by teacherpan** [comment]
修改为：
描述：获取某区域下的所有技术机构实体列表
<hr />
数据请求：
方法：`get`
参数`districtId`(区域ID）
<hr />
数据返回:
```
[
{
"id": 1,
"name": "技术机构一",
"pingyin": "yi"
},
{
"id": 2,
"name": "技术机构二",
"pingyin": "er"
},
{
"id": 3,
"name": "技术机构三",
"pingyin": "san"
},
{
"id": 4,
"name": "技术机构四",
"pingyin": "si"
}
]
```

**Comment by teacherpan** [comment]
DONE
