### ISSUE TITLE
验证用户名是否存在

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#963]

**Comment by liuxiqian** [comment]
获取不到 后台 数据，并报错 GET http://api.measurement.mengyunzhi.cn:8080/User/checkUsernameIsExist/ 404 ()，需要后台写checkUsernameIsExist方法

**Comment by teacherpan** [comment]
http://api.measurement.mengyunzhi.cn:8080/User/checkUsernameIsExist/username 
username不能为空

**Comment by liuxiqian** [comment]
根据不同的用户名 类型确定其显示不同的字段信息
